/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.sistemaEgresado.gui.vista;

import co.edu.eam.ingesoft.desarrollo.sistemaEgresado.gui.controlador.ControladorVentanaEmpresa;
import co.edu.eam.ingesoft.desarrollo.sistemaEgresado.persistencia.modelo.entidades.Ciudad;
import co.edu.eam.ingesoft.desarrollo.sistemaEgresado.persistencia.modelo.entidades.ContactoEmpresa;
import co.edu.eam.ingesoft.desarrollo.sistemaEgresado.persistencia.modelo.entidades.Departamento;
import co.edu.eam.ingesoft.desarrollo.sistemaEgresado.persistencia.modelo.entidades.Empresa;
import co.edu.eam.ingesoft.desarrollo.sistemaEgresado.persistencia.modelo.entidades.Pais;
import co.edu.eam.ingesoft.desarrollo.sistemaEgresado.persistencia.modelo.entidades.SectorLaboral;
import java.util.List;

/**
 *
 * @author Cristian Sinisterra
 */
public class VentanaEmpresa extends javax.swing.JFrame {
    ControladorVentanaEmpresa controlador;
    /**
     * Creates new form VentanaEmpresa
     */
    public VentanaEmpresa() {
        initComponents();
        controlador= new ControladorVentanaEmpresa();
        try {
            listar();
            listarSector();
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }
    
     public void  listar()throws Exception{
    	jCBPais.removeAllItems();
    	jCBPais.addItem("Seleccione un pais");
        List<Pais> lista=controlador.listarPais();
    	for(int i=0; i<lista.size(); i++){
			jCBPais.addItem(lista.get(i));
			
		
		}
    	      	
    }
     
     public void  listarSector()throws Exception{
    	jCBSectorLaboral.removeAllItems();
    	jCBSectorLaboral.addItem("Seleccione un pais");
        List<SectorLaboral> lista=controlador.listarSectorLaboral();
    	for(int i=0; i<lista.size(); i++){
			jCBSectorLaboral.addItem(lista.get(i));
			
		
		}
    	      	
    }
     
      public void cargarDepartamento(List<Departamento> lista) {
        jCBDepartamento.removeAllItems();
        if (lista != null) {
            jCBDepartamento.addItem("Seleccione un Departamento");
            for (int i = 0; i < lista.size(); i++) {
                jCBDepartamento.addItem(lista.get(i));
            }
        } else {
            jCBDepartamento.addItem(null);
        }
    }
      
      
       public void cargarCiudad(List<Ciudad> lista) {
        jCBCiudad.removeAllItems();
        if (lista != null) {
            jCBCiudad.addItem("Seleccione una ciudad");
            for (int i = 0; i < lista.size(); i++) {
                jCBCiudad.addItem(lista.get(i));
            }
        } else {
            jCBCiudad.addItem(null);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFRazonSocial = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jTFDireccion = new javax.swing.JTextField();
        jTFPaginaWeb = new javax.swing.JTextField();
        jCBPais = new javax.swing.JComboBox();
        jCKBPublica = new javax.swing.JCheckBox();
        jCKBPrivada = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jCBDepartamento = new javax.swing.JComboBox();
        jCBCiudad = new javax.swing.JComboBox();
        jCBSectorLaboral = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTFCodigoEmpresa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTNombreContacto = new javax.swing.JTextField();
        jTFCargo = new javax.swing.JTextField();
        jTFTelefonoCon = new javax.swing.JTextField();
        jTFCorreoContacto = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLRegistroEmpresa = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 204, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(252, 230, 181));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 68, 68));
        jLabel1.setText("Razon social:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 68, 68));
        jLabel2.setText("Pais:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 68, 68));
        jLabel3.setText("Telefono:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 68, 68));
        jLabel4.setText("Tipo Empresa:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 68, 68));
        jLabel8.setText("Ciudad:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 68, 68));
        jLabel7.setText("Direccion:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 68, 68));
        jLabel9.setText("P. Web:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 68, 68));
        jLabel10.setText("Sector laboral:");

        jTFRazonSocial.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTFRazonSocial.setForeground(new java.awt.Color(68, 68, 68));
        jTFRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRazonSocialActionPerformed(evt);
            }
        });

        jTFTelefono.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(68, 68, 68));

        jTFDireccion.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTFDireccion.setForeground(new java.awt.Color(68, 68, 68));

        jTFPaginaWeb.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTFPaginaWeb.setForeground(new java.awt.Color(68, 68, 68));

        jCBPais.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jCBPais.setForeground(new java.awt.Color(68, 68, 68));
        jCBPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un país" }));
        jCBPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBPaisItemStateChanged(evt);
            }
        });

        jCKBPublica.setBackground(new java.awt.Color(252, 230, 181));
        jCKBPublica.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jCKBPublica.setForeground(new java.awt.Color(68, 68, 68));
        jCKBPublica.setText("Publica");

        jCKBPrivada.setBackground(new java.awt.Color(252, 230, 181));
        jCKBPrivada.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jCKBPrivada.setForeground(new java.awt.Color(68, 68, 68));
        jCKBPrivada.setText("Privada");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(68, 68, 68));
        jLabel11.setText("Departamento:");

        jCBDepartamento.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jCBDepartamento.setForeground(new java.awt.Color(68, 68, 68));
        jCBDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Departamento" }));
        jCBDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBDepartamentoItemStateChanged(evt);
            }
        });

        jCBCiudad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jCBCiudad.setForeground(new java.awt.Color(68, 68, 68));
        jCBCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Ciudad" }));

        jCBSectorLaboral.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jCBSectorLaboral.setForeground(new java.awt.Color(68, 68, 68));
        jCBSectorLaboral.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un sector laboral" }));

        jButton1.setBackground(new java.awt.Color(45, 114, 225));
        jButton1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Siguiente");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 68, 68));
        jLabel6.setText("Codigo Empresa:");

        jTFCodigoEmpresa.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTFCodigoEmpresa.setForeground(new java.awt.Color(68, 68, 68));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCKBPublica)
                                .addGap(18, 18, 18)
                                .addComponent(jCKBPrivada))
                            .addComponent(jTFTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jCBCiudad, 0, 314, Short.MAX_VALUE)
                            .addComponent(jCBDepartamento, 0, 314, Short.MAX_VALUE)
                            .addComponent(jCBPais, 0, 314, Short.MAX_VALUE)
                            .addComponent(jTFRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jTFCodigoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBSectorLaboral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFPaginaWeb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(74, 110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPais, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jCBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCBCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCKBPublica)
                    .addComponent(jCKBPrivada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFPaginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCBSectorLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Datos de la empresa", jPanel1);

        jPanel2.setBackground(new java.awt.Color(252, 230, 181));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 68, 68));
        jLabel5.setText("Nombre Completo:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(68, 68, 68));
        jLabel12.setText("Cargo:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(68, 68, 68));
        jLabel13.setText("Telefono:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(68, 68, 68));
        jLabel14.setText("Correo electronico:");

        jTNombreContacto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTNombreContacto.setForeground(new java.awt.Color(68, 68, 68));

        jTFCargo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTFCargo.setForeground(new java.awt.Color(68, 68, 68));
        jTFCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCargoActionPerformed(evt);
            }
        });

        jTFTelefonoCon.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTFTelefonoCon.setForeground(new java.awt.Color(68, 68, 68));
        jTFTelefonoCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTelefonoConActionPerformed(evt);
            }
        });

        jTFCorreoContacto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTFCorreoContacto.setForeground(new java.awt.Color(68, 68, 68));

        jButton3.setBackground(new java.awt.Color(45, 114, 225));
        jButton3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCorreoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFTelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jTNombreContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))))
                .addGap(0, 79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTFTelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTFCorreoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contacto", jPanel2);

        jLRegistroEmpresa.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 30)); // NOI18N
        jLRegistroEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLRegistroEmpresa.setText("REGISTRO EMPRESAS");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banner copia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLRegistroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLRegistroEmpresa)
                        .addGap(29, 29, 29)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRazonSocialActionPerformed

    private void jTFCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCargoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
        int codigoEmpresa= Integer.parseInt(jTFCodigoEmpresa.getText());
        String razonSocial= jTFRazonSocial.getText();
        Pais pais= (Pais) jCBPais.getSelectedItem();
        Ciudad ciudad= (Ciudad)jCBCiudad.getSelectedItem();
        String telefono= jTFTelefono.getText();
        SectorLaboral sectorL=(SectorLaboral) jCBSectorLaboral.getSelectedItem();
        String direccion=jTFDireccion.getText();
        String tipo="";
        if(jCKBPublica.isSelected()){
             tipo= jCKBPrivada.getLabel();
        }else if(jCKBPrivada.isSelected()){
            tipo=jCKBPublica.getLabel();
        }
        String pagina=jTFPaginaWeb.getText();
        Empresa empresa= new Empresa(codigoEmpresa, razonSocial, telefono, pais.getPais(), tipo, direccion, pagina, sectorL, ciudad);
        
        String NombreC=jTNombreContacto.getText();
        String TelefonoC=jTFTelefonoCon.getText();
        String cargo= jTFCargo.getText();
        String correoC=jTFCorreoContacto.getText();
        ContactoEmpresa contacto= new ContactoEmpresa(codigoEmpresa, empresa, NombreC, telefono, cargo, correoC);
        contacto.setEmpresa(empresa);
        controlador.editarEmpresa(empresa, contacto);
        }catch(Exception e1){
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTFTelefonoConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTelefonoConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTelefonoConActionPerformed

    private void jCBPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBPaisItemStateChanged
        // TODO add your handling code here:
        try {
            if (jCBPais.getSelectedIndex() == 0) {
                cargarDepartamento(null);
            } else {
                Pais facu = (Pais) jCBPais.getSelectedItem();
                if(facu == null){
                    return;
                }
                
                List<Departamento> evals = controlador.listarDepartamento(facu);
                cargarDepartamento(evals);
            }
        } catch (Exception exc) {
            
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jCBPaisItemStateChanged

    private void jCBDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBDepartamentoItemStateChanged
        // TODO add your handling code here:
        try {
            if (jCBPais.getSelectedIndex() == 0) {
                cargarDepartamento(null);
            } else {
                Pais facu = (Pais) jCBPais.getSelectedItem();
                if(facu == null){
                    return;
                }
                
                List<Departamento> evals = controlador.listarDepartamento(facu);
                cargarDepartamento(evals);
            }
        } catch (Exception exc) {
            
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jCBDepartamentoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;

    private javax.swing.JLabel jLRegistroEmpresa;

    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    public javax.swing.JComboBox jCBCiudad;
    public javax.swing.JComboBox jCBDepartamento;
    public javax.swing.JComboBox jCBPais;
    public javax.swing.JComboBox jCBSectorLaboral;
    public javax.swing.JCheckBox jCKBPrivada;
    public javax.swing.JCheckBox jCKBPublica;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextField jTFCargo;
    public javax.swing.JTextField jTFCodigoEmpresa;
    public javax.swing.JTextField jTFCorreoContacto;
    public javax.swing.JTextField jTFDireccion;
    public javax.swing.JTextField jTFPaginaWeb;
    public javax.swing.JTextField jTFRazonSocial;
    public javax.swing.JTextField jTFTelefono;
    public javax.swing.JTextField jTFTelefonoCon;
    public javax.swing.JTextField jTNombreContacto;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
